-- AlterTable
ALTER TABLE `Commission` ADD COLUMN `settlement_ending_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `settlement_period` ENUM('WEEKLY', 'BI_WEEKLY', 'MONTHLY') NOT NULL DEFAULT 'MONTHLY',
    ADD COLUMN `settlement_starting_from` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
